name: code-quality

on:
  pull_request:
  push:
  workflow_dispatch:
    inputs:
      ignore_cache:
        description: "Ignore the repository cache for this run"
        required: false
        default: "false"

jobs:
  dirty-waters:
    runs-on:
        ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup JDK17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build project
        # We need to build the agent first, because the tests depend on it
        run: mvn clean install -DskipTests

      - name: Dirty Waters Analysis
        uses: chains-project/dirty-waters-action@ea2a1333be991704671dc3010cf2f66fd4f5b035
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_manager: maven
          project_repo: ${{ github.repository }}
          latest_commit_sha: ${{ github.sha }}
          github_event_before: ${{github.event.before}}
